version: "3.8"
services:
  web-app:
    build: .
    depends_on:
      - mongo-db
      - minio-storage

  mongo-db:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb

  minio-storage:
    image: minio/minio:latest
    command: minio server /data --address :9000 --console-address :9001
    volumes:
      - minio-data:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}

  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    command: tunnel run --token ${TUNNEL_TOKEN}
    depends_on:
      - web-app

volumes:
  mongo-config:
    driver: local
  mongo-data:
    driver: local
  minio-data:
    driver: local
